name: Publish to GHCR

on:
  push:
    branches:
      - master
    tags:
      - "*"

env:
  IMAGE_NAME: drawpile-tools

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg DRAWPILE_VERSION=$VERSION

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          echo "Pushing :$VERSION..."
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          [ "$VERSION" != "master" ] \
            && echo "Pushing :latest..." \
            && docker tag $IMAGE_NAME $IMAGE_ID:latest \
            && docker push $IMAGE_ID:latest

          echo "All done!"
